"""Enrich the mining dashboard feed with cohort aggregates and per-individual
records, computed from the real model predictions joined to the deterministic
synthetic mining cohort attributes (seed 7, n=5800, validated to match
predictions 1:1 on actual absence hours).

The cohort / individual / HR-ops computation lives in feed_enrich.py and is
shared with the sector feed builder (build_sector_feeds.py). This script is the
mining entry point: it reproduces the mining cohort, joins it to the committed
predictions, and rewrites data/outputs/dashboard_feed.json / .js.
"""
from __future__ import annotations
import os, sys, json
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)
from welo_pipeline.adapters.synthetic import SyntheticMiningAdapter
import feed_enrich

# ---- load real model output + reproduce attributes -------------------------
preds = pd.read_csv(f"{ROOT}/data/outputs/predictions.csv")
syn = SyntheticMiningAdapter(n_rows=5800, random_seed=7,
                             cohort="glencore_sa_mining").load()
df = preds.merge(syn, on="employee_id", how="left", suffixes=("", "_attr"))
syn_mask = df["source_dataset"].str.startswith("synthetic").fillna(False)
df = df[syn_mask].copy()
assert (df["actual_absent_hours"].round() == df["absence_duration_hours"].round()).all()

# ---- enrich the committed base feed ----------------------------------------
feed = json.load(open(f"{ROOT}/data/outputs/dashboard_feed.json"))
feed, cohorts, individuals, n_hi, n_rest = feed_enrich.enrich(feed, df, sample_n=400, seed=7)

for d in feed_enrich.DIMENSIONS:
    print("\n==", d["label"], "==")
    for c in cohorts[d["key"]]:
        print(f"  {c['label']:>20}  n={c['count']:>4}  hi/crit={c['high_or_critical_share']*100:4.1f}%  "
              f"days/head/yr={c['absent_days_per_head_annual']:5.1f}  meanFatigue={c['mean_fatigue']}")
print("\nindividuals shipped:", len(individuals), "(High/Crit:", n_hi, "+ sample:", n_rest, ")")
hh = feed["hr_ops"]["headline"]
print(f"\nHR & Ops: absence rate {hh['absence_rate']*100:.1f}%  cover-gap {hh['cover_gap_days_90d']:,.0f}d  "
      f"RTW {hh['rtw_caseload']}  freq-trigger {hh['freq_trigger_count']}")

# ---- write enriched feed ----------------------------------------------------
out_json = f"{ROOT}/data/outputs/dashboard_feed.json"
json.dump(feed, open(out_json, "w"), indent=2, default=float)
js = ("// Auto-generated by welo_pipeline.export (+cohort/individual enrichment). Do not edit by hand.\n"
      "// Source: dashboard_feed.json\n"
      "window.WELO_FEED = " + json.dumps(feed, indent=2, default=float) + ";\n")
open(f"{ROOT}/data/outputs/dashboard_feed.js", "w").write(js)
print("\nwrote", out_json, os.path.getsize(out_json), "bytes")
