"""Build sector dashboard feeds (manufacturing, logistics).

Generates a sector-calibrated synthetic cohort, scores it with the SAME
persisted model as mining (one model, different populations), then runs the
shared enrichment to produce data/outputs/dashboard_feed.<sector>.json / .js.
Global feature importance and model metrics are reused from the trained model,
since the model itself is unchanged; SHAP per-row reasons are omitted for the
sector cohorts, so the dashboard shows indicative drivers there.
"""
from __future__ import annotations
import os, sys, json
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

from welo_pipeline.features import build_features
from welo_pipeline.score import score
from welo_pipeline.export import build_dashboard_feed
import sector_cohorts
import feed_enrich

THRESHOLDS = {"low": 4, "medium": 16, "high": 40}  # from configs/demo.yaml
MODELS_DIR = f"{ROOT}/models"

# Reuse the trained model's global importance + metrics (model is unchanged).
_mining = json.load(open(f"{ROOT}/data/outputs/dashboard_feed.json"))
GLOBAL_IMPORTANCE = pd.DataFrame(_mining["global_feature_importance"])
METRICS = json.load(open(f"{ROOT}/reports/model_metrics.json"))


def build_sector(sector: str) -> dict:
    cohort = sector_cohorts.generate_cohort(sector, n_rows=6000, random_seed=7)
    bundle = build_features(cohort, THRESHOLDS)
    pred = score(bundle, models_dir=MODELS_DIR)

    explanations = {"global_importance": GLOBAL_IMPORTANCE, "per_row_reasons": {}}
    feed = build_dashboard_feed(pred, METRICS, explanations, run_name=f"welo_{sector}_v1")

    # join predictions to cohort attributes for the cohort/individual views
    df = pred.merge(cohort, on="employee_id", how="left", suffixes=("", "_attr"))
    feed, cohorts, individuals, n_hi, n_rest = feed_enrich.enrich(feed, df, sample_n=400, seed=7)

    out_json = f"{ROOT}/data/outputs/dashboard_feed.{sector}.json"
    json.dump(feed, open(out_json, "w"), indent=2, default=float)
    js = ("// Auto-generated by build_sector_feeds.py. Do not edit by hand.\n"
          f"// Sector: {sector}\n"
          "window.WELO_FEED = " + json.dumps(feed, indent=2, default=float) + ";\n")
    open(f"{ROOT}/data/outputs/dashboard_feed.{sector}.js", "w").write(js)

    hh = feed["hr_ops"]["headline"]
    h = feed["headline"]
    print(f"\n=== {sector} ===")
    print(f"  covered lives: {h['covered_lives']}  predicted absent days 90d: {h['predicted_absent_days_90d']:,.0f}")
    print(f"  absence rate: {hh['absence_rate']*100:.1f}%  fatigue high/crit: {h['fatigue_high_or_critical_share']*100:.1f}%")
    rd = {b['band']: b['share'] for b in feed['risk_distribution']}
    print("  risk dist: " + "  ".join(f"{k}={v*100:.1f}%" for k, v in rd.items()))
    for d in feed_enrich.DIMENSIONS:
        if d["key"] != "cohort_lifestyle":
            continue
        for c in cohorts[d["key"]]:
            print(f"    {c['label']:>20}  n={c['count']:>4}  hi/crit={c['high_or_critical_share']*100:4.1f}%  "
                  f"days/head/yr={c['absent_days_per_head_annual']:5.1f}")
    print(f"  individuals shipped: {len(individuals)} (High/Crit {n_hi} + sample {n_rest})")
    return feed


if __name__ == "__main__":
    for s in ["manufacturing", "logistics"]:
        build_sector(s)
    print("\ndone.")
